# This is a basic workflow to help you get started with Actions

name: GH Commit Stats

# Controls when the workflow will run
on:
  # schedule:
  #   - cron: "*/5 * * * *"
  push:
    # paths: 
    #   - 'scripts/test.sh'
    #   - 'workflows/GH_Stats.yml'
  workflow_dispatch: 
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: GH Commit Stats
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a shell script to fetch commits from the repository  
      - name: Run test script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPOSITORY: ${{ github.repository }}
        run: |
          # chmod +x ./scripts/test.sh
          # ./scripts/test.sh
          gh run list -w "GH Commit Stats"
      - name: Get typescript version
        run: |
          npx tsc --version
